engines:
  tailor:
    enabled: true
    checks:
      forced-type-cast:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
       - swift
fixme:
    enabled: true
ratings:
  paths: 
  - Mockit/Classes/**
  - Example/Tests/**
  - Example/Mockit/**
  - “**.swift”
exclude_paths: 
- Example/Mockit/Base.lproj/**
- Example/Mockit/Image.xcassets/*
- Example/Mockit/Info.plist
- Example/Pods/**
- Example/Mockit.xcworkspace/**
- Example/Mockit.xcodeproj/**
- Example/Podfile
- Example/Podfile.lock
- LICENSE
- README.md
- Mockit.podspec
